### ISSUE TITLE
hot module reload stops working with this plugin

### ISSUE THREAD

**Issue by panigrah** [Derek-Hu/react-app-rewire-multiple-entry#9] opened 2020-02-14 00:49 UTC
to recreate 
1. start with default cra app template. `yarn create create-react`
2. add the following packages.
```
    "customize-cra": "^0.9.1",
    "react": "^16.12.0",
    "react-app-rewire-multiple-entry": "^2.0.1",
    "react-app-rewired": "^2.1.5",
```
3. provide simple configuration in `config-overrides.js`
```
const multipleEntry = require('react-app-rewire-multiple-entry')([
  {
    entry: 'src/index.js',
    outPath: 'index.html'
  },
  {
    entry: 'src/index2.js',
    outPath: 'index2.html'
  }
]);

module.exports = override(
  multipleEntry.addMultiEntry
);
```

4. start the app 
`react-app-rewired start -p 3000`

**Comment by Derek-Hu** [comment] 2020-03-06 10:53
Cannot Reproduce, Please give me an example!

**Comment by rhendric** [comment] 2020-04-22 06:41
Here's a batteries-included example: https://github.com/rhendric/congenial-fiesta

It's just the basic `create-react-app` setup, with an `index2.js` literally copied from `index.js`, and with `react-app-rewire-multiple-entry` plugged in as above, except gated by an environment variable. If you run **`react-app-rewired start`** and make an edit to `App.js`, you can see the web app reload with the change. If you run **`REACT_REFRESH=1 react-app-rewired start`** (which enables [`customize-cra-react-refresh`](https://github.com/esetnik/customize-cra-react-refresh)), you can make edits to `App.js` and see them updated in the web app without even a reload flicker. Prefixing **`MULTIPLE_ENTRY=1`** (which enables `react-app-rewire-multiple-entry`) to either of the above commands breaks both update mechanisms; no edits to `App.js` show up in either `index.html` or `index2.html` until the web app is manually reloaded.

**Comment by Arkellys** [comment] 2020-04-28 09:07
I just got the same problem with the following config:

```JS
const multipleEntry = require('react-app-rewire-multiple-entry')([
   {
      entry: 'src/index.js',
      template: 'public/index.html',
      outPath: '/index.html'
   },
   {
      entry: 'src/worker.js',
      template: 'public/worker.html',
      outPath: 'worker.html'
   }
]);
```

After checking the config returned with `addMultiEntry()`, I noticed that the default CRA entry for `index.js` is not removed, so it is not necessary to add it to the `multipleEntry` list. After removing it, the hot-reload worked again.

**Comment by Arkellys** [comment] 2020-04-29 13:35
So, after working with the new config for a few hours, I can tell the hot-reload is still partially broken. :/ It works fine when I update a component, but not when I edit any non-component file. I tried to manually add the new entry without using the plugin but I'm facing the same issue.

**Comment by rhendric** [comment] 2020-04-29 15:13
I believe the root issue here is https://github.com/webpack/webpack/issues/10762. That issue has already been fixed, but the [backport to webpack 4](https://github.com/webpack/webpack/pull/10776) is still pending. In the meantime, I've been able to work around this by inserting this function into my config-overrides:
```
config => (config.optimization.splitChunks.name = process.env.NODE_ENV === 'development', config)
```

**Comment by Arkellys** [comment] 2020-04-29 17:48
After trying the new config for a few hours I noticed that the hot-reload was only working partially. Any change on a component was triggering a refresh (as it should) while changes on a non-component file were only updating the console.

I just tried your fix @rhendric  and it solved the issue! Thanks :)

**Comment by tuanddd** [comment] 2020-05-01 15:46
At first it does send the hot update json in the network but no UI changes is visible right away, only after a manual refresh did the changes showed up
I tried @rhendric's solution and it did changed but it's not HMR anymore and instead a browser refresh?

**Comment by rhendric** [comment] 2020-07-26 16:38
I just tested this with webpack forced to version 4.44.0 (the first in the 4 series to be released with the backported fix) and could not reproduce. I think this issue can be closed now.

**Comment by Derek-Hu** [comment] 2020-08-06 07:54
it is possible to use [react-app-rewire-hot-loader](https://github.com/cdharris/react-app-rewire-hot-loader) to setup React-hot-loader without ejecting.

**Closed** 2020-08-06 07:55 UTC
